import { defaultLocale, type Locale } from "./config";

export type LandingDict = {
  locale: Locale;
  dir: "ltr";
  meta: { title: string; description: string };
  scarcity: { label: string; plazas: string; reserve: string };
  nav: { features: string; howItWorks: string; pricing: string; faq: string; tools: string; login: string; startFree: string; open: string };
  hero: {
    badge: string; titleLine1: string; titleHighlight: string; titleLine3: string; subtitle: string;
    ctaPrimary: string; ctaWeb: string; ctaNoInstall: string; downloadFree: string; cancelAnytime: string;
    excelente: string; reviews: string; coaching: string; athletes: string; stats: Array<{ v: string; l: string; sub: string }>;
  };
  mock: { today: string; streak: string; sessions: string; adherence: string; muscle: string; todayWorkout: string; workoutTitle: string; workoutMeta: string; start: string; nextCheckin: string; energy: string; review: string; sync: string };
  steps: { badge: string; title: string; titleMuted: string; subtitle: string; cards: Array<{ n: string; t: string; d: string }>; cta: string; join: string };
  testimonials: { badge: string; title: string; subtitle: string; cards: Array<{ name: string; change: string; quote: string; gain: string; img: string | null }> };
  features: {
    badge: string; title: string; title2: string; subtitle: string; cards: Array<{ title: string; desc: string }>;
    forTrainers: string; trainerTitle: string; bullets: string[]; tryFree: string; seeDemo: string; useWherever: string;
    syncedTitle: string; syncedDesc: string; openWeb: string; downloadApp: string; tiktokHint: string;
  };
  pricing: {
    badge: string; title: string; title2: string; subtitle: string; popular: string; freeTrial: string; guarantee: string;
    guaranteeDesc: string; noRisk: string; footer: string;
    plans: Array<{ name: string; price: string; cad: string; desc: string; feats: string[]; cta: string; featured: boolean }>;
  };
  finalCta: { title: string; subtitle: string; openBrowser: string; createFree: string; tiktokTitle: string; step1: string; step2: string; step3: string; copyLink: string; months: string; support: string; protected: string };
  faq: { badge: string; title: string; subtitle: string; items: Array<{ q: string; a: string }>; contact: string };
  footer: { rights: string; made: string; privacy: string; terms: string; cookies: string; license: string; contact: string };
};

export const dictionaries: Record<Locale, LandingDict> = {
  es: {
    locale: "es", dir: "ltr",
    meta: { title: "KinetixFitt - Transforma tu Cuerpo, Domina tu Mente", description: "La plataforma todo-en-uno que combina ciencia del deporte, IA personalizada y comunidad para resultados que duran para siempre." },
    scarcity: { label: "ESCASEZ REAL:", plazas: "17 plazas Pro", reserve: "Reservar mi plaza" },
    nav: { features: "Funcionalidades", howItWorks: "Cómo funciona", pricing: "Planes", faq: "FAQ", tools: "Herramientas", login: "Ingresar", startFree: "Empezar gratis", open: "Abrir app en navegador" },
    hero: {
      badge: "Coaching personalizado", titleLine1: "Consigue un físico", titleHighlight: "estético y fuerte", titleLine3: "progresando con ciencia",
      subtitle: "La plataforma de KINETIXFITT que une programación inteligente, nutrición precisa y seguimiento real. Sin humo, solo progresión.",
      ctaPrimary: "Comenzar mi transformación", ctaWeb: "Usar en web", ctaNoInstall: "· sin instalar", downloadFree: "Descarga gratuita · Cancela cuando quieras",
      cancelAnytime: "Cancelá cuando quieras", excelente: "Experiencia KinetixFitt", reviews: "—", coaching: "Coaching personalizado", athletes: "Atletas"
      stats: [{ v: "—", l: "Atletas activos", sub: "dato en preparación" }, { v: "—", l: "Entrenamientos", sub: "dato en preparación" }, { v: "—", l: "Valoración", sub: "sin dato publicado" }, { v: "—", l: "Retención", sub: "sin dato publicado" }],
    },
    mock: { today: "Dashboard · Hoy", streak: "Racha 14 días 🔥", sessions: "Sesiones", adherence: "Adherencia", muscle: "Músculo", todayWorkout: "Entrenamiento de hoy", workoutTitle: "Pecho · Hombro · Tríceps", workoutMeta: "5 ejercicios · 60 min · RIR 2", start: "COMENZAR →", nextCheckin: "Próximo check-in", energy: "En 2 días · Energía 8/10", review: "KinetixFitt revisa en 24h →", sync: "App lista · Web y móvil sincronizados" },
    steps: {
      badge: "Tres pilares del producto", title: "Tres pilares que aseguran", titleMuted: "tu progreso real", subtitle: "Sin motivación vacía. Ciencia + sistema + seguimiento humano.",
      cards: [{ n: "01", t: "Motivación que no falla", d: "Rachas, XP, rangos y misiones. No dependés de ganas: el sistema te empuja." }, { n: "02", t: "Programación con progresión", d: "Programación adaptada al objetivo y contexto configurados por el atleta, con seguimiento de progresión." }, { n: "03", t: "Progresión responsable", d: "El producto ayuda a registrar técnica, RIR y carga; no sustituye criterio profesional ni garantiza ausencia de lesiones." }],
      cta: "Comenzar mi transformación →", join: "Empezá con una cuenta y construí tu proceso",
    },
    testimonials: {
      badge: "Historias reales", title: "Resultados que hablan", subtitle: "Aquí lideramos con ejemplo. Atletas reales, datos reales.",
      cards: [
        { name: "Toñete", change: "Perdió 15kg en 3 meses", quote: "Me estanqué años por no saber progresar. Con Kinetix no me preocupo más. 100% recomendado para ganar músculo.", gain: "-15kg", img: null },
        { name: "Sofía R.", change: "Ganó 8kg músculo", quote: "La racha y los rangos me hicieron constante por primera vez. Resultados en semanas.", gain: "+8kg", img: null },
        { name: "Lucas P.", change: "+40% composición", quote: "Progreso automático por planificación personalizada. Todo el que quiera estética debe probarlo.", gain: "+40%", img: null },
        { name: "Valentina M.", change: "Madre · Recuperó figura post-parto", quote: "Entreno 3×/semana en casa con mis bandas. El plan se adapta a mi tiempo. Volví a sentirme yo.", gain: "12 sem", img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face" },
        { name: "Martín S.", change: "Emprendedor · -9kg sin cardio extremo", quote: "Nutrición precisa + entrenamiento inteligente. Bajé grasa manteniendo músculo. Nunca pasé hambre.", gain: "-9kg", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face" },
      ],
    },
    features: {
      badge: "Funcionalidades principales", title: "Todo lo que necesitás,", title2: "en una sola app", subtitle: "Programación, nutrición, progreso y comunidad. Sin spreadsheets, sin WhatsApps perdidos.",
      cards: [{ title: "Plan Personalizado", desc: "1 clic. Adaptado a tu cuerpo, objetivo y material." }, { title: "Cálculo Automático", desc: "Sobrecarga progresiva: te dice cuánto levantar." }, { title: "Rangos & Gamificación", desc: "Subí de rango según tu nivel real. XP, rachas, badges." }, { title: "Red Social Privada", desc: "Compartí progreso con tu entrenador y amigos." }],
      forTrainers: "Para entrenadores — TrueCoach style", trainerTitle: "Menos admin, más coaching", bullets: ["Public Profiles: web para captar clientes en tu link de bio", "Program Builder: escribí una vez, personalizá por cliente", "Client Management: todo en un lugar — check-ins, pagos, progreso", "Compliance 7/30/90: ves quién cumple y quién necesita atención"],
      tryFree: "Probar 14 días gratis", seeDemo: "Ver demo", useWherever: "Usá donde quieras", syncedTitle: "Web + Móvil, sincronizados", syncedDesc: "Entrená en el gimnasio con el móvil, analizá en casa en la web. Progreso, check-ins y mensajes 100% sincronizados.", openWeb: "Abrir en web", downloadApp: "Descargar app", tiktokHint: "Si TikTok no deja abrir la tienda: ⋯ → Abrir en navegador",
    },
    pricing: {
      badge: "Planes", title: "Invertí en tu salud,", title2: "sin letra chica", subtitle: "Cancelá cuando quieras. Sin contratos. 14 días de prueba, sin tarjeta.", popular: "Más popular", freeTrial: "7 días gratis, luego $19/mes", guarantee: "Garantía 30 días sin preguntas", guaranteeDesc: "Si no ves progreso, te devolvemos el 100%. Sin letra chica. El riesgo es nuestro.", noRisk: "Sin riesgo", footer: "Precios en USD · Impuestos incluidos · Podés cambiar de plan en cualquier momento",
      plans: [{ name: "Básico", price: "$0", cad: "/mes", desc: "Para arrancar", feats: ["50+ ejercicios", "Seguimiento básico", "Comunidad"], cta: "Crear cuenta gratis", featured: false }, { name: "Pro Athlete", price: "$19", cad: "/mes", desc: "Para resultados serios", feats: ["Todo Básico", "Rutinas con IA", "Nutrición + macros", "Analíticas avanzadas", "Soporte prioritario"], cta: "Comenzar prueba gratis", featured: true }, { name: "Elite Coach", price: "$49", cad: "/mes", desc: "1 a 1 con tu coach", feats: ["Todo Pro", "Coach humano", "Ajustes semanales", "Eventos exclusivos"], cta: "Aplicar ahora", featured: false }],
    },
    finalCta: { title: "Tu transformación comienza hoy", subtitle: "Usalo en web sin instalar, o descargá la app. Tu progreso vive en ambos.", openBrowser: "Abrir en navegador", createFree: "Crear cuenta gratis", tiktokTitle: "¿TikTok no te deja abrir la tienda?", step1: "Pulsá los tres puntos ⋯ arriba a la derecha", step2: "Elegí “Abrir en el navegador”", step3: "Volvé a pulsar descarga — o usá “Abrir en navegador” directo", copyLink: "Copiar enlace del app", months: "3 meses transformación", support: "Soporte humano", protected: "Datos protegidos" },
    faq: { badge: "FAQ", title: "Preguntas frecuentes", subtitle: "Transparencia total. Si no está acá, escribinos y respondemos en 24h.", items: [{ q: "¿Necesito material o gimnasio?", a: "No. El plan se adapta a tu material (bandas, mancuernas, peso corporal o gym completo). Elegís al onboarding y lo cambiás cuando quieras." }, { q: "¿Cómo funciona la prueba gratis de 14 días?", a: "Acceso total a Pro sin tarjeta. Al día 14 elegís continuar a $19/mes o quedarte en Básico gratis. Te avisamos 2 días antes. Sin sorpresas." }, { q: "¿Qué pasa si me lesiono o me voy de viaje?", a: "Pausás con 1 clic. La racha se congela 7 días y el plan se reajusta a tu vuelta. Progresión sin culpa, adherencia a largo plazo." }, { q: "¿Es para mujeres también?", a: "Absolutamente. 43% de nuestras atletas son mujeres. Planes específicos para fuerza, glúteos, recomposición y post-parto. Misma ciencia, objetivos tuyos." }, { q: "¿En qué se diferencia de Symmetry / TrueCoach?", a: "Symmetry es contenido + comunidad; TrueCoach es solo para entrenadores. Kinetix une ambos: IA que programa + humano que corrige + gamificación que retiene. Todo en una app web+móvil." }, { q: "¿Mis datos están protegidos? ¿Venden mis datos?", a: "Nunca vendemos datos. Cifrado AES-256, RGPD + Ley 25.326 AR. Podés exportar o borrar todo con 1 clic. Ver Privacidad y Cookies." }], contact: "¿Otra duda? Escribinos — respondemos en 24h" },
    footer: { rights: "© 2026 KINETIXFITT. Todos los derechos reservados.", made: "Hecho con ♥ en Argentina · Cumplimos Ley 25.326, LGPD y GDPR. No vendemos tus datos.", privacy: "Privacidad", terms: "Términos", cookies: "Cookies", license: "Licencia", contact: "Contacto" },
  },
  en: {
    locale: "en", dir: "ltr",
    meta: { title: "KinetixFitt — Transform Your Body, Master Your Mind", description: "The all-in-one platform that blends sports science, personalized AI and community for results that last forever." },
    scarcity: { label: "REAL SCARCITY:", plazas: "17 Pro spots left", reserve: "Reserve my spot" },
    nav: { features: "Features", howItWorks: "How it works", pricing: "Pricing", faq: "FAQ", tools: "Tools", login: "Log in", startFree: "Start free", open: "Open app in browser" },
    hero: {
      badge: "Personalized coaching", titleLine1: "Build an aesthetic,", titleHighlight: "strong physique", titleLine3: "with science-based progression", subtitle: "The KINETIXFITT platform that brings together smart programming, precise nutrition and real coaching. No fluff, just progression.",
      ctaPrimary: "Start my transformation", ctaWeb: "Use on web", ctaNoInstall: "· no install", downloadFree: "Free download · Cancel anytime", cancelAnytime: "Cancel anytime", excelente: "KinetixFitt experience", reviews: "—", coaching: "Personalized coaching", athletes: "Athletes"
      stats: [{ v: "—", l: "Active athletes", sub: "data pending" }, { v: "—", l: "Workouts", sub: "data pending" }, { v: "—", l: "Rating", sub: "not published" }, { v: "—", l: "Retention", sub: "not published" }],
    },
    mock: { today: "Dashboard · Today", streak: "14-day streak 🔥", sessions: "Sessions", adherence: "Adherence", muscle: "Muscle", todayWorkout: "Today's workout", workoutTitle: "Chest · Shoulders · Triceps", workoutMeta: "5 exercises · 60 min · RIR 2", start: "START →", nextCheckin: "Next check-in", energy: "In 2 days · Energy 8/10", review: "KinetixFitt reviews in 24h →", sync: "App ready · Web & mobile in sync" },
    steps: { badge: "Three product pillars", title: "Three pillars that ensure", titleMuted: "real progress", subtitle: "No empty motivation. Science + system + human coaching.", cards: [{ n: "01", t: "Unbreakable motivation", d: "Streaks, XP, ranks and quests. You don't rely on willpower: the system pushes you." }, { n: "02", t: "Progressive programming", d: "Programming adapted to the athlete context with progression tracking." }, { n: "03", t: "Responsible progression", d: "The product helps track technique, RIR and load; it does not replace professional judgment or guarantee no injuries." }], cta: "Start my transformation →", join: "Start with an account and build your process" },
    testimonials: { badge: "Real stories", title: "Results that speak", subtitle: "We lead by example. Real athletes, real data.", cards: [{ name: "Toñete", change: "Lost 15kg in 3 months", quote: "I was stuck for years not knowing how to progress. With Kinetix I don't worry anymore. 100% recommended to build muscle.", gain: "-15kg", img: null }, { name: "Sofía R.", change: "Gained 8kg muscle", quote: "Streaks and ranks made me consistent for the first time. Results in weeks.", gain: "+8kg", img: null }, { name: "Lucas P.", change: "+40% body comp", quote: "Automatic progress from personalized planning. Anyone who wants aesthetics should try it.", gain: "+40%", img: null }, { name: "Valentina M.", change: "Mom · Post-partum comeback", quote: "I train 3×/week at home with bands. The plan adapts to my time. I feel like myself again.", gain: "12 wks", img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face" }, { name: "Martín S.", change: "Founder · -9kg without extreme cardio", quote: "Precise nutrition + smart training. I cut fat while keeping muscle. Never starved.", gain: "-9kg", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face" }] },
    features: { badge: "Core features", title: "Everything you need,", title2: "in one app", subtitle: "Programming, nutrition, progress and community. No spreadsheets, no lost WhatsApps.", cards: [{ title: "Personalized Plan", desc: "1 click. Adapted to your body, goal and equipment." }, { title: "Automatic Calculation", desc: "Progressive overload: tells you how much to lift." }, { title: "Ranks & Gamification", desc: "Level up based on real level. XP, streaks, badges." }, { title: "Private Social Network", desc: "Share progress with your coach and friends." }], forTrainers: "For coaches — TrueCoach style", trainerTitle: "Less admin, more coaching", bullets: ["Public Profiles: web to capture clients in your bio link", "Program Builder: write once, personalize per client", "Client Management: everything in one place — check-ins, payments, progress", "Compliance 7/30/90: see who is compliant and who needs attention"], tryFree: "Try 14 days free", seeDemo: "View demo", useWherever: "Use anywhere", syncedTitle: "Web + Mobile, in sync", syncedDesc: "Train at the gym on mobile, analyze at home on web. Progress, check-ins and messages 100% synced.", openWeb: "Open on web", downloadApp: "Download app", tiktokHint: "If TikTok blocks the store: ⋯ → Open in browser" },
    pricing: { badge: "Pricing", title: "Invest in your health,", title2: "no fine print", subtitle: "Cancel anytime. No contracts. 14-day trial, no card required.", popular: "Most popular", freeTrial: "7 days free, then $19/mo", guarantee: "30-day no-questions guarantee", guaranteeDesc: "If you don't see progress, we refund 100%. No fine print. The risk is on us.", noRisk: "No risk", footer: "Prices in USD · Taxes included · Switch plans anytime", plans: [{ name: "Basic", price: "$0", cad: "/mo", desc: "To get started", feats: ["50+ exercises", "Basic tracking", "Community"], cta: "Create free account", featured: false }, { name: "Pro Athlete", price: "$19", cad: "/mo", desc: "For serious results", feats: ["Everything in Basic", "AI routines", "Nutrition + macros", "Advanced analytics", "Priority support"], cta: "Start free trial", featured: true }, { name: "Elite Coach", price: "$49", cad: "/mo", desc: "1:1 with your coach", feats: ["Everything in Pro", "Human coach", "Weekly adjustments", "Exclusive events"], cta: "Apply now", featured: false }] },
    finalCta: { title: "Your transformation starts today", subtitle: "Use it on the web without installing, or download the app. Your progress lives in both.", openBrowser: "Open in browser", createFree: "Create free account", tiktokTitle: "TikTok blocking the store?", step1: "Tap the three dots ⋯ at top right", step2: "Choose “Open in browser”", step3: "Tap download again — or use “Open in browser” directly", copyLink: "Copy app link", months: "3-month transformation", support: "Human support", protected: "Data protected" },
    faq: { badge: "FAQ", title: "Frequently asked questions", subtitle: "Total transparency. If it's not here, email us and we reply in 24h.", items: [{ q: "Do I need equipment or a gym?", a: "No. The plan adapts to your equipment (bands, dumbbells, bodyweight or full gym). Choose at onboarding and change anytime." }, { q: "How does the 14-day free trial work?", a: "Full Pro access without a card. On day 14 choose to continue at $19/mo or stay on Basic free. We notify you 2 days before. No surprises." }, { q: "What if I get injured or travel?", a: "Pause in 1 click. Streak freezes for 7 days and the plan readjusts when you're back. Progression without guilt, long-term adherence." }, { q: "Is it for women too?", a: "Absolutely. 43% of our athletes are women. Specific plans for strength, glutes, recomposition and post-partum. Same science, your goals." }, { q: "How is it different from Symmetry / TrueCoach?", a: "Symmetry is content + community; TrueCoach is for coaches only. Kinetix brings both together: AI that programs + human that corrects + gamification that retains. All in one web+mobile app." }, { q: "Is my data protected? Do you sell data?", a: "We never sell data. AES-256 encryption, GDPR + AR Law 25.326. You can export or delete everything in 1 click. See Privacy & Cookies." }], contact: "Another question? Email us — we reply in 24h" },
    footer: { rights: "© 2026 KINETIXFITT. All rights reserved.", made: "Made with ♥ in Argentina · We comply with Law 25.326, LGPD and GDPR. We never sell your data.", privacy: "Privacy", terms: "Terms", cookies: "Cookies", license: "License", contact: "Contact" },
  },
};

export function getDictionary(locale: Locale): LandingDict {
  return dictionaries[locale] ?? dictionaries[defaultLocale];
}
